# Docker Compose version 2
version: "2"
services:
  # application tier container
  app:
    # Use the version 1 image in the private registry
    image: registry.ca-labs.com:5000/accumulator:1
    ports:
      - "80:8080"
    # Ensure the app container starts after app-db
    depends_on:
      - app-db
  # database tier container
  app-db:
    image: mongo:3