# Docker Compose version 3
version: "3"
services:
  # appliction tier container
  app:
    # Use the version 1 image in the private registry
    image: registry.ca-labs.com:5000/accumulator:1
    ports:
      - "80:8080"
  # database tier container
  app-db:
    image: mongo:3